### ISSUE TITLE
 .ics file is not working in Edge

### ISSUE THREAD

**Issue by hzrcan** [jshor/datebook#94]
It is not possible to download an .ics file in the Edge browser.

See below:
![datebook-edge](https://user-images.githubusercontent.com/3510239/84779320-8bbc5000-afe4-11ea-96e4-ce78eea8a368.png)

Can this be solved please?

**Comment by jshor** [comment]
This issue is caused by Edge containing the word "Safari" in its `userAgent` string. Because of this, a Safari-specific workaround (that doesn't work in Edge) was used to download ICS files instead of `FileSaver.saveAs()`.

PR #95 which fixes this will be merged soon.

**Comment by hzrcan** [comment]
Thanks bro.

Op wo 17 jun. 2020 om 21:12 schreef Josh Shor <notifications@github.com>:

**Comment by hzrcan** [comment]
Dear Josh,

When will you release this version?
Waiting for the fix..
It’s not released yet.

Kind regards,
Hizir

Verstuurd vanaf mijn iPhone

**Comment by jshor** [comment]
datebook@4.1.4 is published and should fix the issue.

**Comment by hzrcan** [comment]
I still get the same error when I upgrade the version to 4.1.4. See:

![edge](https://user-images.githubusercontent.com/3510239/85989280-9ae1cb80-b9f0-11ea-95f7-c6222938099b.png)


Do I need to change something else?

**Comment by hzrcan** [comment]
Looks like the issue has been fixed in version 4.1.5. Thanks.
